### ISSUE TITLE
Teams - `code` tags showing in sidebar nav

### ISSUE THREAD

**Issue by jamespohalloran** [tinacms/tinacms-site#121]
<img width="1063" alt="Screen Shot 2019-11-06 at 3 32 37 PM" src="https://user-images.githubusercontent.com/3323181/68331107-c6532700-00aa-11ea-98ce-e163613e9054.png">
Not sure if this is a site layout issue, or an issue with my nav in the markdown

**Comment by kendallstrautman** [comment]
Closed in new site, no more right-hand TOC
