### ISSUE TITLE
post: Custom fields with TinaCMS

### ISSUE THREAD

**Issue by DirtyF** [tinacms/tinacms-site#133]
Blog post idea suggested by @scottgallant 

**Step 1.** Explain why you would want to make a custom field
**Step 2.** Make a super basic custom input field so people get the gist. 

For example:
```js
// Replace the "text" component from this field with a function
// export default remarkForm(BlogPostTemplate, {
//   fields: [
//     { name: "frontmatter.title", component: "text", label: "Title" }
//   ]
// })

// Like this

export default remarkForm(BlogPostTemplate, {
  fields: [
    { name: "frontmatter.title", 
     component: ({ input }) => { return <input style={{ background: "blue", color: "white"}} {...input} /> },
     label: "Title", description: "The title of this post" }
  ]
})
```

**Step 3.**  Show a slightly more useful example: a color picker field that pulls a specific color palette from a JSON file, like so:

![image](https://user-images.githubusercontent.com/103008/69148780-5cd50e80-0ad5-11ea-85a3-44d7c05ae95d.png)

**Comment by kendallstrautman** [comment]
similar to #23
