### ISSUE TITLE
Hard redirect on the tinacms documentation page

### ISSUE THREAD

**Issue by IronSean** [tinacms/tinacms-site#182]
If you click `Documentation` on the tinacms website to get to the documentation site, it directs you to https://tinacms.org/docs/. When this page fully loads and the js initializes, it then redirects to https://tinacms.org/docs/getting-started/introduction. 

You can no longer use the browser back button to return to the page you were on previously at this point, as it returns you to `/docs` which immediately (as the js is now cached) redirects to `/docs/getting-started/introduction` again.

This should be a `history.replace` instead of a `history.push` to replace the history record and let back take you to the location before `/docs` most likely.

**Comment by mittonface** [comment]
![tina](https://user-images.githubusercontent.com/5082908/71026335-03adca00-20d7-11ea-9d6f-55f44d251f59.gif)

Here's a video of reproduction. I navigate to `/docs/` and then am unable to navigate back to my previous content using the browser's back button.
