### ISSUE TITLE
Update Docs for tinacms#544

### ISSUE THREAD

**Issue by DirtyF** [tinacms/tinacms-site#195]
A [pull request](https://github.com/tinacms/tinacms/pull/544) in tinacms may require documentation updates.

The following files may need to be updated:

| File | Reason |
| --- | --- |
| [backends.md](https://github.com/tinacms/tinacms-site/tree/master//content/docs/concepts/backends.md) | Explains creating a custom Express backend |,
| [configure-git-plugin.md](https://github.com/tinacms/tinacms-site/tree/master//content/docs/gatsby/configure-git-plugin.md) | Describes GitRouterConfig interface |,
| [adding-backends.md](https://github.com/tinacms/tinacms-site/tree/master//content/docs/nextjs/adding-backends.md) | Demonstrates using Express server |,
| [using-tinacms-with-nextjs.md](https://github.com/tinacms/tinacms-site/tree/master//content/blog/using-tinacms-with-nextjs.md) | Uses tina-git-server |

**Comment by kendallstrautman** [comment]
I don't think anything needs to be updated considering the changes?
