### ISSUE TITLE
Document `next-tinacms-json` default object workaround

### ISSUE THREAD

**Issue by kendallstrautman** [tinacms/tinacms-site#233]
See notes from — https://github.com/tinacms/tinacms/issues/676

**Comment by alexbarbato** [comment]
Ah, I started working on a very minor pr for this, but it looks like you may be handling this in your next docs pr #232

Please holler if not!

**Comment by kendallstrautman** [comment]
Nice! No that PR has other info about using the helpers. Feel free to open one up! That’d be awesome. Thank you 😊
