### ISSUE TITLE
Adding a "Draft" flag to your Gatsby blog

### ISSUE THREAD

**Issue by ncphillips** [tinacms/tinacms-site#26]
If you setup your gatsby site to support draft posts, then on your post index you can add something like this:

```
<Link style={{ boxShadow: `none` }} to={node.fields.slug}>
   {title}{" "}
   {node.frontmatter.draft && (
   <small style={{ color: "fuchsia" }}>Draft</small>
  )}
</Link>
```

That way you can easily see which posts are drafts while you're browsing the site.

**Comment by ncphillips** [comment]
I'm thinking we build this guide off `gastby-starter-tinacms`. We could use that starter to create a `tinacms/example-gatsby-blog` repository and clearly show each of the steps in the blog post as individual commits. The blog post could link to those commits as a reference for the reader

Maybe @spbyrne could add some nice `draft` indicators on the index and blog-post templates?

**Comment by kendallstrautman** [comment]
published
