### ISSUE TITLE
Add a "Tip" or "Info" block.

### ISSUE THREAD

**Issue by ncphillips** [tinacms/tinacms-site#7]
Some helpful comments don't fit the flow of a doc. It would be good to have a Tip/Info/Warning block for these comments. E.g. the second sentence is about contributing rather than editing.

<img width="715" alt="image" src="https://user-images.githubusercontent.com/824015/64711103-7cc1d380-d48f-11e9-8435-54cabb32d1eb.png">

**Comment by kendallstrautman** [comment]
Believe this is available now using `<tip>` in the md editor
